import { Link } from "wouter";
import { ArrowRight, ExternalLink } from "lucide-react";
import { PageContainer } from "@/components/Layout";
import { WelcomeBanner } from "./WelcomeBanner";
import { LiveStatsStrip } from "./LiveStatsStrip";
import { BestYieldCard } from "./BestYieldCard";
import { WhaleActivityCard } from "./WhaleActivityCard";
import { MarketMoversCard } from "./MarketMoversCard";
import { FeaturedStrategyCard } from "./FeaturedStrategyCard";
import { ExpiringSoonList } from "./ExpiringSoonList";

export function SimpleHome() {
  return (
    <PageContainer>
      <WelcomeBanner />

      {/* Hero */}
      <div className="mb-8 text-center md:text-left">
        <img src="./brand/boros-by-pendle-logo.svg" alt="UseBoros" className="h-12 md:h-14 w-auto mb-4 mx-auto md:mx-0" />
        <h1 className="font-display text-3xl md:text-4xl font-bold tracking-tight mb-3">Yield tools for Pendle & Boros</h1>
        <p className="text-base text-muted-foreground mb-5 max-w-xl mx-auto md:mx-0">
          Model portfolios, compare yields, discover opportunities — built on live Pendle data.
        </p>
        <div className="flex gap-3 justify-center md:justify-start">
          <Link href="/portfolio">
            <span className="inline-flex items-center gap-1.5 teal-cta text-sm px-5 py-2.5 rounded-lg cursor-pointer">
              Portfolio Builder <ArrowRight className="w-3.5 h-3.5" />
            </span>
          </Link>
          <Link href="/yields">
            <span className="inline-flex items-center gap-1.5 text-sm px-5 py-2.5 rounded-lg border border-primary/40 text-primary hover:bg-primary/10 cursor-pointer">
              Explore Yields <ArrowRight className="w-3.5 h-3.5" />
            </span>
          </Link>
        </div>
      </div>

      <LiveStatsStrip variant="compact" />

      <div className="mb-8">
        <h2 className="font-display text-lg font-semibold mb-4">What's happening right now</h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <BestYieldCard variant="compact" />
          <WhaleActivityCard variant="compact" />
          <MarketMoversCard variant="compact" />
          <FeaturedStrategyCard variant="compact" />
        </div>
      </div>

      <ExpiringSoonList variant="compact" />

      {/* What is Pendle */}
      <div id="what-is-pendle" className="mb-12" data-testid="what-is-pendle">
        <h2 className="font-display text-lg font-semibold mb-4">What is Pendle?</h2>
        <div className="bg-card border border-card-border rounded-xl p-6 space-y-4">
          <p className="text-sm text-muted-foreground leading-relaxed">
            <a href="https://www.pendle.finance" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">Pendle</a> is a DeFi protocol that lets you <span className="text-foreground font-medium">tokenize and trade future yield</span>. Think of it like bond stripping in traditional finance — you take a yield-bearing asset (like staked ETH) and split it into two separate tokens:
          </p>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div className="bg-background/50 rounded-lg p-4 border border-border/30">
              <p className="text-xs font-semibold text-primary mb-1">PT — Principal Token</p>
              <p className="text-xs text-muted-foreground leading-relaxed">
                Represents the principal. Buy PT at a discount, redeem it for the full underlying asset at maturity. This is how you <span className="text-foreground">lock in a fixed yield</span>.
              </p>
              <div className="mt-3 bg-background rounded p-2.5 border border-border/20">
                <p className="text-[11px] font-mono text-muted-foreground">
                  <span className="text-foreground">Example:</span> Buy PT-stETH at 5% implied APY with 1-year maturity. For every 0.95 ETH you spend, you get 1 ETH back at maturity — guaranteed 5% return.
                </p>
              </div>
            </div>
            <div className="bg-background/50 rounded-lg p-4 border border-border/30">
              <p className="text-xs font-semibold text-secondary mb-1">YT — Yield Token</p>
              <p className="text-xs text-muted-foreground leading-relaxed">
                Represents the yield stream. Holding YT gives you all the yield generated by the underlying asset until maturity. This is how you <span className="text-foreground">go long on yields</span>.
              </p>
              <div className="mt-3 bg-background rounded p-2.5 border border-border/20">
                <p className="text-[11px] font-mono text-muted-foreground">
                  <span className="text-foreground">Example:</span> Buy 10 YT-stETH. You receive all the staking yield from 10 ETH until expiry. If the average APY exceeds what you paid, you profit.
                </p>
              </div>
            </div>
          </div>

          <p className="text-xs text-muted-foreground leading-relaxed">
            Pendle's AMM is purpose-built for yield trading — it adjusts its curve as tokens approach maturity, concentrating liquidity and improving capital efficiency. LPs earn from PT fixed yield, underlying SY yield, swap fees, and PENDLE incentives. All PT and YT trades happen through a single PT/SY liquidity pool using flash swaps.
          </p>

          <div className="flex items-center gap-4 pt-1">
            <a href="https://docs.pendle.finance" target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1 text-xs text-primary hover:underline">
              Read the docs <ExternalLink className="w-3 h-3" />
            </a>
            <a href="https://app.pendle.finance/trade/markets" target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1 text-xs text-primary hover:underline">
              Explore markets <ExternalLink className="w-3 h-3" />
            </a>
          </div>
        </div>
      </div>

      {/* What is Boros */}
      <div id="what-is-boros" className="mb-12" data-testid="what-is-boros">
        <h2 className="font-display text-lg font-semibold mb-4">What is Boros?</h2>
        <div className="bg-card border border-card-border rounded-xl p-6 space-y-4">
          <p className="text-sm text-muted-foreground leading-relaxed">
            <a href="https://boros.pendle.finance" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">Boros</a> is Pendle's <span className="text-foreground font-medium">interest rate swap platform for perpetual funding rates</span>. While Pendle V2 handles yield from staking and lending, Boros focuses on the massive funding rate market from perpetual futures — a $150B+ daily market across Binance, Bybit, Hyperliquid, and more.
          </p>

          <div className="bg-background/50 rounded-lg p-4 border border-border/30">
            <p className="text-xs font-semibold text-foreground mb-2">How it works</p>
            <div className="space-y-2.5">
              <div className="flex items-start gap-3">
                <div className="flex items-center justify-center w-5 h-5 rounded-full bg-primary/20 text-primary text-[10px] font-bold shrink-0 mt-0.5">1</div>
                <p className="text-xs text-muted-foreground"><span className="text-foreground">Deposit collateral</span> into a trading zone (e.g., ETH zone). Each zone can have multiple markets sharing the same base asset.</p>
              </div>
              <div className="flex items-start gap-3">
                <div className="flex items-center justify-center w-5 h-5 rounded-full bg-primary/20 text-primary text-[10px] font-bold shrink-0 mt-0.5">2</div>
                <p className="text-xs text-muted-foreground"><span className="text-foreground">Open an interest rate swap.</span> You either pay fixed and receive floating, or receive fixed and pay floating — depending on your view on where rates are heading.</p>
              </div>
              <div className="flex items-start gap-3">
                <div className="flex items-center justify-center w-5 h-5 rounded-full bg-primary/20 text-primary text-[10px] font-bold shrink-0 mt-0.5">3</div>
                <p className="text-xs text-muted-foreground"><span className="text-foreground">Manage your position</span> with cross-margin or isolated margin modes. Each market has a Mark Rate (TWAP oracle) for fair unrealized P&L valuation.</p>
              </div>
            </div>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
            <div className="bg-background/50 rounded-lg p-3 border border-border/30">
              <p className="text-[11px] font-semibold text-primary mb-1">For Yield Seekers</p>
              <p className="text-[11px] text-muted-foreground leading-relaxed">Lock in a fixed funding rate via a cash-and-carry strategy: long spot + short perp + fix rate on Boros = predictable yield.</p>
            </div>
            <div className="bg-background/50 rounded-lg p-3 border border-border/30">
              <p className="text-[11px] font-semibold text-secondary mb-1">For Hedgers</p>
              <p className="text-[11px] text-muted-foreground leading-relaxed">Already running a perp position? Swap your floating funding rate to fixed on Boros. Eliminate funding rate uncertainty entirely.</p>
            </div>
            <div className="bg-background/50 rounded-lg p-3 border border-border/30">
              <p className="text-[11px] font-semibold text-chart-4 mb-1">For Speculators</p>
              <p className="text-[11px] text-muted-foreground leading-relaxed">Think rates will rise or fall? Go long or short on the rate itself with leverage. Pure directional exposure to funding rates.</p>
            </div>
          </div>

          <div className="flex items-center gap-4 pt-1">
            <a href="https://boros.pendle.finance" target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1 text-xs text-primary hover:underline">
              Trade on Boros <ExternalLink className="w-3 h-3" />
            </a>
            <Link href="/strategies">
              <span className="inline-flex items-center gap-1 text-xs text-primary hover:underline cursor-pointer">
                View strategies <ExternalLink className="w-3 h-3" />
              </span>
            </Link>
          </div>
        </div>
      </div>
    </PageContainer>
  );
}
